
name: Generate Snake

on:
  # Jalankan otomatis setiap 24 jam (00:00 UTC)
  schedule:
    - cron: "0 0 * * *"
  # Memungkinkan dijalankan manual dari tab Actions
  workflow_dispatch:
  # Jalankan tiap ada push ke branch main
  push:
    branches:
      - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1. Generate gambar SVG animasi ular dari grid kontribusi akrom-code
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: akrom-code
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 2. Simpan hasil gambar ke branch 'output'
      - name: Push github-contribution-grid-snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
